/* @flow */
export const ANSWER = 'ANSWER'
export const REFRESH_QUESTION = 'REFRESH_QUESTION'

export const FETCH_WORDSET_REQUEST = 'FETCH_WORDSET_REQUEST'
export const FETCH_WORDSET_FAILURE = 'FETCH_WORDSET_FAILURE'
export const FETCH_WORDSET_SUCCESS = 'FETCH_WORDSET_SUCCESS'
